/**
 * State management — Zustand stores for domain, chat, and KB state.
 */

export { useDomainStore } from './domain-store'
export { useChatStore } from './chat-store'
export type { ChatMessage } from './chat-store'
export { useKBStore } from './kb-store'
export { useIntakeStore } from './intake-store'
export { useSettingsStore } from './settings-store'
export { useProtocolStore } from './protocol-store'
export { useSessionStore } from './session-store'
export { useGapFlagStore } from './gap-flag-store'
export { useAuditStore } from './audit-store'
export { useDecisionStore } from './decision-store'
export { useRelationshipStore } from './relationship-store'
export { useBriefingStore } from './briefing-store'
export { useDeadlineStore } from './deadline-store'
export { useAdvisoryStore } from './advisory-store'
export { useAutomationStore } from './automation-store'
export { useToastStore } from './toast-store'
export { useTagStore } from './tag-store'
export { useSkillStore } from './skill-store'
export { useMissionStore } from './mission-store'
export { usePluginStore } from './plugin-store'
export { useCommandStore } from './command-store'
