# Funding links for DomainOS
# Uncomment and fill in when sponsorship channels are set up.

# github: [username]
# open_collective: domain-os
# ko_fi: username
# custom: ["https://example.com/sponsor"]
